import type { CollegePreference, FileRecord } from "./types";

const DISTRICTS = ["Chennai", "Coimbatore", "Madurai", "Salem", "Tiruchirappalli", "Tirunelveli", "Vellore", "Erode"];

const COLLEGE_POOL: { name: string; location: string }[] = [
  { name: "Anna University", location: "Chennai, Tamil Nadu" },
  { name: "SRM Institute of Science & Technology", location: "Kattankulathur, Tamil Nadu" },
  { name: "VIT University", location: "Vellore, Tamil Nadu" },
  { name: "Madurai Medical College", location: "Madurai, Tamil Nadu" },
  { name: "PSG College of Arts & Science", location: "Coimbatore, Tamil Nadu" },
  { name: "Coimbatore Institute of Technology", location: "Coimbatore, Tamil Nadu" },
  { name: "Loyola College", location: "Chennai, Tamil Nadu" },
  { name: "Bharathiar University", location: "Coimbatore, Tamil Nadu" },
];

const PARTNER_NAMES = ["Bright Future Edu", "NextStep Consultants", "EduPath Advisors", "Scholar Bridge", "Career Compass"];

function collegePreferencesFor(index: number): CollegePreference[] {
  return [0, 1, 2].map((offset) => {
    const college = COLLEGE_POOL[(index + offset) % COLLEGE_POOL.length];
    return { rank: offset + 1, name: college.name, location: college.location };
  });
}

// Fields not carried by RAW_RECORDS below are deterministically derived from
// each record's index rather than hand-written per row — this is mock data
// standing in for a future detail API, not meaningful business data.
type RawFileRecord = Omit<
  FileRecord,
  "regNo" | "passedOutYear" | "district" | "collegePreferences" | "submittedAt" | "submittedBy"
>;

const RAW_RECORDS: RawFileRecord[] = [
  {
    id: "FILE-1001",
    partnerId: "PT-501",
    studentName: "Rahul Kumar",
    studentMobile: "+91 9876543210",
    lookingFor: "B.Tech Admission",
    submittedDate: "20 Jul 2026",
    paymentStatus: "Advance",
    status: "Pending",
    stage: "approve",
  },
  {
    id: "FILE-1002",
    partnerId: "PT-315",
    studentName: "Priya Sharma",
    studentMobile: "+91 9123456780",
    lookingFor: "MBA",
    submittedDate: "19 Jul 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "approve",
  },
  {
    id: "FILE-1003",
    partnerId: "PT-208",
    studentName: "Arjun Reddy",
    studentMobile: "+91 9988776655",
    lookingFor: "MBBS",
    submittedDate: "18 Jul 2026",
    paymentStatus: "Balance Pending",
    status: "Rejected",
    stage: "approve",
  },
  {
    id: "FILE-1004",
    partnerId: "PT-402",
    studentName: "Sneha Iyer",
    studentMobile: "+91 9845098450",
    lookingFor: "M.Tech",
    submittedDate: "17 Jul 2026",
    paymentStatus: "Advance",
    status: "Pending",
    stage: "approve",
  },
  {
    id: "FILE-1005",
    partnerId: "PT-556",
    studentName: "Karan Mehta",
    studentMobile: "+91 9812345098",
    lookingFor: "BBA",
    submittedDate: "16 Jul 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "approve",
  },
  {
    id: "FILE-1006",
    partnerId: "PT-233",
    studentName: "Divya Nair",
    studentMobile: "+91 9765432109",
    lookingFor: "MCA",
    submittedDate: "15 Jul 2026",
    paymentStatus: "Balance Pending",
    status: "Pending",
    stage: "approve",
  },
  {
    id: "FILE-1007",
    partnerId: "PT-678",
    studentName: "Vikram Singh",
    studentMobile: "+91 9900112233",
    lookingFor: "BCA",
    submittedDate: "14 Jul 2026",
    paymentStatus: "Advance",
    status: "Approved",
    stage: "approve",
  },
  {
    id: "FILE-1008",
    partnerId: "PT-119",
    studentName: "Anjali Gupta",
    studentMobile: "+91 9871234560",
    lookingFor: "Diploma",
    submittedDate: "13 Jul 2026",
    paymentStatus: "Final Amount",
    status: "Rejected",
    stage: "approve",
  },
  {
    id: "FILE-1009",
    partnerId: "PT-345",
    studentName: "Rohan Das",
    studentMobile: "+91 9822334455",
    lookingFor: "B.Tech Admission",
    submittedDate: "12 Jul 2026",
    paymentStatus: "Balance Pending",
    status: "Pending",
    stage: "approve",
  },
  {
    id: "FILE-1010",
    partnerId: "PT-812",
    studentName: "Neha Kapoor",
    studentMobile: "+91 9098765432",
    lookingFor: "MBA",
    submittedDate: "11 Jul 2026",
    paymentStatus: "Advance",
    status: "Approved",
    stage: "approve",
  },
  {
    id: "FILE-1011",
    partnerId: "PT-267",
    studentName: "Suresh Babu",
    studentMobile: "+91 9700998877",
    lookingFor: "MBBS",
    submittedDate: "10 Jul 2026",
    paymentStatus: "Final Amount",
    status: "Pending",
    stage: "approve",
  },
  {
    id: "FILE-1012",
    partnerId: "PT-934",
    studentName: "Meera Joshi",
    studentMobile: "+91 9711223344",
    lookingFor: "M.Tech",
    submittedDate: "09 Jul 2026",
    paymentStatus: "Balance Pending",
    status: "Approved",
    stage: "approve",
  },
  {
    id: "FILE-1013",
    partnerId: "PT-471",
    studentName: "Farhan Khan",
    studentMobile: "+91 9812309876",
    lookingFor: "BBA",
    submittedDate: "08 Jul 2026",
    paymentStatus: "Advance",
    status: "Rejected",
    stage: "reject",
  },
  {
    id: "FILE-1014",
    partnerId: "PT-289",
    studentName: "Ishita Rao",
    studentMobile: "+91 9654321890",
    lookingFor: "MCA",
    submittedDate: "07 Jul 2026",
    paymentStatus: "Balance Pending",
    status: "Rejected",
    stage: "reject",
  },
  {
    id: "FILE-1015",
    partnerId: "PT-663",
    studentName: "Aditya Verma",
    studentMobile: "+91 9123045678",
    lookingFor: "BCA",
    submittedDate: "06 Jul 2026",
    paymentStatus: "Final Amount",
    status: "Rejected",
    stage: "reject",
  },
  {
    id: "FILE-1016",
    partnerId: "PT-190",
    studentName: "Pooja Menon",
    studentMobile: "+91 9988001122",
    lookingFor: "Diploma",
    submittedDate: "05 Jul 2026",
    paymentStatus: "Advance",
    status: "Rejected",
    stage: "reject",
  },
  {
    id: "FILE-1017",
    partnerId: "PT-758",
    studentName: "Manoj Pillai",
    studentMobile: "+91 9845612370",
    lookingFor: "B.Tech Admission",
    submittedDate: "04 Jul 2026",
    paymentStatus: "Balance Pending",
    status: "Rejected",
    stage: "reject",
  },
  {
    id: "FILE-1018",
    partnerId: "PT-524",
    studentName: "Kavya Reddy",
    studentMobile: "+91 9712345678",
    lookingFor: "MBA",
    submittedDate: "03 Jul 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "final",
  },
  {
    id: "FILE-1019",
    partnerId: "PT-337",
    studentName: "Siddharth Rao",
    studentMobile: "+91 9876001122",
    lookingFor: "MBBS",
    submittedDate: "02 Jul 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "final",
  },
  {
    id: "FILE-1020",
    partnerId: "PT-905",
    studentName: "Ananya Sharma",
    studentMobile: "+91 9887766554",
    lookingFor: "M.Tech",
    submittedDate: "01 Jul 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "final",
  },
  {
    id: "FILE-1021",
    partnerId: "PT-146",
    studentName: "Vivek Nair",
    studentMobile: "+91 9900998877",
    lookingFor: "BBA",
    submittedDate: "30 Jun 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "final",
  },
  {
    id: "FILE-1022",
    partnerId: "PT-382",
    studentName: "Ritu Malhotra",
    studentMobile: "+91 9123456701",
    lookingFor: "MCA",
    submittedDate: "29 Jun 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "final",
  },
  {
    id: "FILE-1023",
    partnerId: "PT-617",
    studentName: "Abhinav Sen",
    studentMobile: "+91 9812233445",
    lookingFor: "BCA",
    submittedDate: "28 Jun 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "final",
  },
  {
    id: "FILE-1024",
    partnerId: "PT-249",
    studentName: "Lakshmi Iyer",
    studentMobile: "+91 9765098450",
    lookingFor: "Diploma",
    submittedDate: "27 Jun 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "final",
  },
  {
    id: "FILE-1025",
    partnerId: "PT-871",
    studentName: "Nikhil Bhatt",
    studentMobile: "+91 9988112233",
    lookingFor: "B.Tech Admission",
    submittedDate: "26 Jun 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "final",
  },
  {
    id: "FILE-1026",
    partnerId: "PT-703",
    studentName: "Swati Desai",
    studentMobile: "+91 9845123670",
    lookingFor: "MBA",
    submittedDate: "25 Jun 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "closed",
  },
  {
    id: "FILE-1027",
    partnerId: "PT-418",
    studentName: "Harish Kumar",
    studentMobile: "+91 9123980045",
    lookingFor: "MBBS",
    submittedDate: "24 Jun 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "closed",
  },
  {
    id: "FILE-1028",
    partnerId: "PT-560",
    studentName: "Priyanka Singh",
    studentMobile: "+91 9876120033",
    lookingFor: "M.Tech",
    submittedDate: "23 Jun 2026",
    paymentStatus: "Final Amount",
    status: "Approved",
    stage: "closed",
  },
];

export const INITIAL_FILE_RECORDS: FileRecord[] = RAW_RECORDS.map((record, index) => ({
  ...record,
  regNo: `TN2024-HC-${(29000 + index * 37) % 99999}`,
  passedOutYear: "2024",
  district: DISTRICTS[index % DISTRICTS.length],
  collegePreferences: collegePreferencesFor(index),
  submittedAt: `${record.submittedDate}, 10:34 AM`,
  submittedBy: PARTNER_NAMES[index % PARTNER_NAMES.length],
}));
